// RobotBuilder Version: 4.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

// ROBOTBUILDER TYPE: Subsystem.

package frc.robot.subsystems;


import frc.robot.RobotMap;
import edu.wpi.first.wpilibj.DigitalInput;
import edu.wpi.first.wpilibj2.command.SubsystemBase;

import com.ctre.phoenix.motorcontrol.can.WPI_TalonSRX;

/**
 *
 */
public class Index extends SubsystemBase 
{
    
    private WPI_TalonSRX indexMotor;
    private DigitalInput indexLimitSwitch;

    /**
    *
    */
    public Index() 
    {
        indexMotor = new WPI_TalonSRX(RobotMap.INDEX_MOTOR_TALON_ID);
        indexLimitSwitch = new DigitalInput(RobotMap.INDEX_LIMIT_SWITCH_ID);
    }

    @Override
    public void periodic() 
    {
        // This method will be called once per scheduler run
    }

    @Override
    public void simulationPeriodic() 
    {
        // This method will be called once per scheduler run when in simulation

    }

    // Put methods for controlling this subsystem
    // here. Call these from Commands.

    public void cargo_index_in()
    {
        indexMotor.set(RobotMap.INDEX_MOTOR_SPEED);
    }

    public void cargo_index_out()
    {
        indexMotor.set(-RobotMap.INDEX_MOTOR_SPEED);
    }
    
    public void index_stop()
    {
        indexMotor.stopMotor();
    }

    public boolean is_cargo_in_index()
    {
        return indexLimitSwitch.get();
    }
}

