// RobotBuilder Version: 4.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

// ROBOTBUILDER TYPE: Subsystem.

package frc.robot.subsystems;


import frc.robot.RobotMap;
import edu.wpi.first.wpilibj.DigitalInput;
import edu.wpi.first.wpilibj2.command.SubsystemBase;

import com.ctre.phoenix.motorcontrol.can.WPI_TalonSRX;

/**
 *
 */
public class Intake extends SubsystemBase 
{
    
    private WPI_TalonSRX intakeCargo;
    private WPI_TalonSRX intakeShoulder;
    private DigitalInput intaketoplimitSwitch;

    /**
    *
    */
    public Intake() 
    {
        intakeCargo = new WPI_TalonSRX(RobotMap.INTAKECARGO_TALON_ID);
        intakeShoulder = new WPI_TalonSRX(RobotMap.INTAKESHOULDER_TALON_ID);
        intaketoplimitSwitch = new DigitalInput(RobotMap.INTAKELIMITSWITCH_ID);
    }

    @Override
    public void periodic() 
    {
        // This method will be called once per scheduler run
    }

    @Override
    public void simulationPeriodic() 
    {
        // This method will be called once per scheduler run when in simulation

    }

    // Put methods for controlling this subsystem
    // here. Call these from Commands.

    public void cargointake()
    {
        intakeCargo.set(RobotMap.INTAKECARGO_SPEED);
    }

    public void cargointake_clear()
    {
        intakeCargo.set(-RobotMap.INTAKECARGO_SPEED);
    }

    public void cargointake_stop()
    {
        intakeCargo.stopMotor();
    }

    public void intake_up()
    {
        if (is_intake_up())
        {
            cargointake_stop();
        }
        else 
        { 
            intakeShoulder.set(RobotMap.INTAKESHOULDER_SPEED);
        }
    }

    public void intake_down()
    { 
        intakeShoulder.set(-RobotMap.INTAKESHOULDER_SPEED); 
    }

    public void shoulder_stop()
    {
        intakeShoulder.stopMotor();
    }

    public boolean is_intake_up()
    {
        return intaketoplimitSwitch.get();
    }
}

