// RobotBuilder Version: 4.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

// ROBOTBUILDER TYPE: Subsystem.

package frc.robot.subsystems;


import frc.robot.RobotMap;
import frc.robot.commands.*;
import edu.wpi.first.wpilibj.DigitalInput;
import edu.wpi.first.wpilibj.livewindow.LiveWindow;
import edu.wpi.first.wpilibj2.command.SubsystemBase;

import com.ctre.phoenix.motorcontrol.can.WPI_TalonSRX;
import io.github.pseudoresonance.pixy2api.Pixy2;
import io.github.pseudoresonance.pixy2api.Pixy2CCC;
import io.github.pseudoresonance.pixy2api.Pixy2CCC.Block;
import io.github.pseudoresonance.pixy2api.links.SPILink;
/**
 *
 */
public class Pixie extends SubsystemBase 
{
    private static Pixy2 pixy = null;
    private static double x , y;
    private static boolean ball;

    /**
    *
    */
    public Pixie() 
    {
        // Set the default command for a subsystem here.
        // setDefaultCommand(new MySpecialCommand());
        pixy = Pixy2.createInstance(new SPILink()); // Creates a new Pixy2 camera using SPILink
        pixy.init(); // Initializes the camera and prepares to send/receive data
        pixy.setLamp((byte) 1, (byte) 1); // Turns the LEDs on
        pixy.setLED(255, 255, 255); // Sets the RGB LED to full white  
    }

    @Override
    public void periodic() 
    {
        // This method will be called once per scheduler run
    }

    @Override
    public void simulationPeriodic() 
    {
        // This method will be called once per scheduler run when in simulation

    }

    // Put methods for controlling this subsystem
    // here. Call these from Commands.
    public static Pixy2 getPixyCamera1() {
		return pixy;
  }
  
  public static void getBiggestBlock() 
  {
		// Gets the number of "blocks", identified targets, that match signature 1 on the Pixy2,
		// does not wait for new data if none is available,
		// and limits the number of returned blocks to 25, for a slight increase in efficiency
		int blockCount = pixy.getCCC().getBlocks(false, Pixy2CCC.CCC_SIG1, 25);
		// System.out.println("Found " + blockCount + " blocks!"); // Reports number of blocks found
		if (blockCount > 0)//might need to be >=
		{
			ArrayList<Block> blocks = pixy.getCCC().getBlocks(); // Gets a list of all blocks found by the Pixy2
			Block largestBlock = null;
			for (Block block : blocks) 
			{ // Loops through all blocks and finds the widest one
				if (largestBlock == null) {
					largestBlock = block;
				} else if (block.getWidth() > largestBlock.getWidth()) {
					largestBlock = block;
				}
			
			}
            ball = true;
            x = largestBlock.getX();
			y = largestBlock.getY();
		}
		else
		{
			x = 0;
			y = 0;
			ball = false;
		}


	}
	public double Read_Pixy_x()
	{
		return x;
	}
	public double Read_Pixy_y()
	{
		return y;
	}
	public boolean Read_Pixy_is_Ball()
	{
		return ball;
    }
}
   


